apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-brev
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"

spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
  port: 8001
  liveness:
    path: /api/status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /api/status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: false
  ingresses:
    - https://familie-brev.intern.dev.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-mottak
        - application: familie-ef-sak-frontend
        - application: familie-ba-sak
        - application: familie-ks-sak
        - application: familie-klage
        - application: tilleggsstonader-klage
          namespace: tilleggsstonader
    outbound:
      rules:
        - application: familie-dokument
      external:
        - host: appres.nav.no
        - host: xsrv1mh6.api.sanity.io
        - host: xsrv1mh6.apicdn.sanity.io
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: APPRES_CMS_URL
      value: https://appres.nav.no
    - name: ENV
      value: preprod
  secureLogs:
    enabled: true
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
