apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-brev
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8001
  liveness:
    path: /api/status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /api/status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: false
  ingresses:
    - https://familie-brev.dev.intern.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-sak-frontend
    outbound:
      rules:
        - application: familie-dokument
      external:
        - host: appres.nav.no
        - host: xsrv1mh6.api.sanity.io
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: APPRES_CMS_URL
      value: https://appres.nav.no
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi