name: Build and deploy dev

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v4
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # ratchet:actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          registry-url: "https://npm.pkg.github.com"

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          yarn install --prefer-offline --frozen-lockfile --ignore-scripts
          yarn build
          yarn install --production --prefer-offline --frozen-lockfile --ignore-scripts
      - name: Push docker image to GAR
        uses: nais/docker-build-push@2d2b0a7193e65422b7f0355d4afb445e0a8b2cc3 # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamfamilie
          tag: latest-dev
  deployDev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v4
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
